# Generated by Django 4.0.2 on 2023-10-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_author_remove_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='featured',
        ),
    ]
